config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: {
    sessions: "public/sessions",
    registrations: "public/registrations"
  }

  resources :users,only: [:show,:edit,:update,:index] do
    member do
      get 'followers'
      get 'followings'
    end
    resource :relationships, only: [:create, :destroy]
  end
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create]
  end

  resources :book_comments, only: [:destroy]

  root 'home#top'
  get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord 
	belongs_to :user
	validates :title, presence: true
	validates :body ,presence: true, length: {maximum: 200}

  has_many :favorites, dependent: :destroy 
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    Favorite.where(user_id: user.id, book_id: self.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followee, class_name: 'User'
  belongs_to :follower, class_name: 'User'

  validates :follower_id, presence: true
  validates :followee_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attachment :profile_image, destroy: false
  has_many :books, dependent: :destroy 
  has_many :favorites, dependent: :destroy 
  has_many :book_comments, dependent: :destroy 
  validates :name, presence: true, length: {maximum: 10, minimum: 2}
  validates :introduction, length: {maximum: 50}
  
  # フォローしている人
  has_many :relationships, foreign_key: "follower_id"
  has_many :followings, through: :relationships, source: :followee
  
  # フォロワー
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'followee_id'
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  
  def following?(another_user)
    self.followings.include?(another_user)
  end

  def follow(another_user)
    unless self == another_user
      self.relationships.find_or_create_by(followee_id: another_user.id)
    end
  end
  
  def unfollow(another_user)
    unless self == another_user
      relationship = self.relationships.find_by(followee_id: another_user.id)
      relationship.destroy if relationship
    end
  end

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  
  private
    #sign in後のredirect先変更
    def after_sign_in_path_for(resource)
      user_path(resource)
    end

    #sign out後のredirect先変更
    def after_sign_out_path_for(resource)
      root_path
    end

    #sin up時の登録情報追加
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profle_image, :email])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:name]) # ログイン時にnameを使用
    end
    def correct_user?(user)
      if current_user.nil?
        return false
      else
        user.id.equal?(current_user.id)
      end
    end 
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @comment = current_user.book_comments.new(comment_params)
    @comment.book_id = params[:book_id]
    @comment.save
    #redirect_to books_path
  end

  def destroy
    @comment = BookComment.find(params[:id])
    @book = Book.find(@comment.book_id)
    @comment.destroy
    #redirect_to books_path
  end

  private
  def comment_params
    params.require(:book_comment).permit(:body)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!,only: [:create,:edit,:update,:destroy,:index]

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    screen_user(@book)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to @book
    else
      @books = Book.all
      render 'index'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_url
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def screen_user(book)
      if book.user.id != current_user.id
        redirect_to books_path
      end
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  # POST /books/:book_id/favorites
  # POST /favorites.json
  def create
    if !Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
      @favorite = current_user.favorites.new(:book_id => params[:book_id])
      @favorite.save
      #redirect_to books_path
    end
  end


  # DELETE /books/:book_id/favorites/
  def destroy
    if Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)#.exists?
      @favorite = Favorite.find_by(user_id: current_user, book_id: params[:book_id])
      @book = Book.find_by(id: params[:book_id])
      @favorite.destroy
      #redirect_to books_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to request.referer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :screen_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def followings
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private
    def user_params
       params.require(:user).permit(:name, :introduction, :profile_image)
    end

    def screen_user
      unless params[:id].to_i == current_user.id
        redirect_to user_path(current_user)
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_table.html.erb
<table>
  <% book_comments.each do |comment| %>
    <tr>
      <td><%= attachment_image_tag(comment.user, :profile_image, size: "100x100", fallback: "no-image-icon.jpg") %></td>
      <td><%= comment.body %></td>
      <td><%= link_to "削除", book_comment_path(comment), method: :delete, class: "btn btn-danger", remote: true%></td>
    </tr>
  <% end %>
</table>

app/views/book_comments/create.js.erb
$('#comment__textarea').val('')
$('.book_comment_body').val('')
$('.detail__table').html("<%= j(render 'books/detail', book: @comment.book) %>")
$('.comment__table').html("<%= j(render 'book_comments/table', book_comments: @comment.book.book_comments ) %>")

app/views/book_comments/destroy.js.erb
$('.detail__table').html("<%= j(render 'books/detail', book: @book) %>")
$('.comment__table').html("<%= j(render 'book_comments/table', book_comments: @book.book_comments ) %>")

app/views/books/_detail.html.erb
<table class='table'>
  <tr>
    <td><%= link_to(book.user) do %>
      <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
      <%= book.user.name %>
      <% end %>
    </td>
    <td><%= link_to book.title, book %></td>
    <td><%= book.body %></td>
    <td class=<%= "table__favorite--" +book.id.to_s %>>
      <%= render 'favorites/book', favorites: book.favorites, user: current_user, book: book%>
    </td>
    <td>コメント数: <%= book.book_comments.count %></td>
    <% if book.user == current_user %>
      <td><%= link_to 'Edit', edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_book_#{book.id}"%></td>
    <% end %>
  </tr>
</table>

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body'%>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12'%>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class=<%= "table__favorite--" + book.id.to_s %>>
          <%= render 'favorites/book', book: book, user: current_user%>
        </td>
        <td>コメント数: <%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='row'>
	<div class='col-md-6 col-md-offset-3'>
		<h1>Editing Book</h1>
  <!-- <div class='col-md-3 col-md-offset-3'>
  </div> -->
  	<%= render 'layouts/errors', obj: @book %>
		<%= render 'form', book: @book %>
		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
		<%= link_to 'Back', books_path, class: "back" %>
    </div>
    <div class='col-md-3'></div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: current_user %>

    <h2>New book</h2>
    <%= render 'form', book: @book %>
  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <%= render 'index', books: @books%>
  </div>
</div>

app/views/books/show.html.erb
<div class='row'>
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'users/info', user: @book.user %>
    <h2>New book</h2>
    <%= render 'form', book: Book.new %>
  </div>
  

  <div class='col-xs-9'>
		<h2>Book detail</h2>
    <div class="detail__table">
      <%= render 'detail', book: @book %>
    </div>

    <%= form_with(model: [@book, @comment], remote: true) do |f|%>
      <%= f.text_area :body, class: "book_comment_body" %>
      <%= f.submit "送信", class: "btn btn-primary", id: "comment__textarea" %>
    <% end %>
    <div class="comment__table">
      <%= render 'book_comments/table', book_comments: @book.book_comments%>
    </div>
  </div>
</div>

app/views/favorites/_book.html.erb
<% if book.favorited_by?(user) %>
  <%= link_to book_favorites_path(book.id), method: :delete, remote: true do %>
    <span class="glyphicon glyphicon-heart"><%= book.favorites.count %></span>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book.id), method: :post, remote: true do %>
    <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('.table__favorite--'+<%= @favorite.book_id%>).html("<%= j(render 'favorites/book',  book: @favorite.book, user: @favorite.user ) %>")

app/views/favorites/destroy.js.erb
$('.table__favorite--'+<%= @book.id %>).html("<%= j(render 'favorites/book',  book: @book, user: @book.user ) %>")

app/views/home/about.html.erb
<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>


app/views/home/top.html.erb
<div class="row">
  <div class='top-message col-md-offset-3 col-md-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><%= link_to 'Log in',new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
      </div>
    </div>
            
  </div>
</div>
        

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home',user_path(current_user),class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users',users_path,class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' Books',books_path ,class: 'glyphicon glyphicon-book books'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete,class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home',root_path,class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About',home_about_path,class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path,class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path ,class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

  	<div class='body'>
      <div class='container'>
        
        
        <p id="notice"><%= notice %></p>
      
      	<%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>
          <% unless current_user == user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"btn btn-default"%>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id),method: :post, class:"btn btn-primary"%>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
      <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr> 
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
      <tr> 
        <th>フォロー中</th>
        <th>
          <%= link_to followings_user_path(user) do %>
            <%= user.followings.count %>人
          <% end %>
        </th>
      </tr>
      <tr> 
        <th>フォロワー</th>
        <th>          
          <%= link_to followers_user_path(user) do %>
            <%= user.followers.count %>人
          <% end %>
        </th>
      </tr>
      <% unless current_user == user %>
        <tr>
          <th>
            <% if current_user.following?(user) %>
              <% link_to "フォロー外す", user_relationships_path(user), method: :delete, class:"btn btn-default"%>
            <% else %>
              <% link_to "フォローする", user_relationships_path(user), method: :post, class:"btn btn-primary"%>
            <% end %>
          </th>
        </tr>
      <% end %>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local:true do |f| %>
  <%= render 'layouts/errors', obj: @user %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "name" %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.attachment_field :profile_image, class: "user_image" %>
  </div>

  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "introduction" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/followers.html.erb
<h2><%= current_user==@user?"自分":@user.name%>のフォロワーリスト</h2>
<%= render 'index', users: @user.followers %>

app/views/users/followings.html.erb
<h2><%= current_user==@user?"自分":@user.name%>がフォローしているリスト</h2>
<%= render 'index', users: @user.followings %>

app/views/users/index.html.erb
<div class='row'>
  
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: current_user %>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>

  </div>

  <div class='col-xs-9'>
    <h2>Users</h2>

    <%= render 'index',users: @users %>
  </div>

</div>

app/views/users/show.html.erb
<div class='row'>
  
  <div class='col-xs-3'>
    <h2>User info</h2>
    <%= render 'info', user: @user,now: ''%>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>

  </div>

  <div class='col-xs-9'>
    <h2>Books</h2>

    <%= render 'books/index',books: @books %>
  </div>
</div>